# Generated by Django 4.2.2 on 2025-08-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0008_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='static/assets/imgbase.jpg', null=True, upload_to=''),
        ),
    ]
